In [1]:
import numpy as np                # linear algebra
import pandas as pd               # data processing
import matplotlib.pyplot as plt   # visualisations

import torch                      # PyTorch

In [2]:
data = pd.read_csv("/kaggle/input/notes-table/table notes.png.csv")
data

Eleve  Mathematiques  Physique  Informatique   LV1   LV2  Biologie  Chimie
0   E01           12.6      10.6          14.2  12.3  10.2       9.3     7.7
1   E02           13.9      12.9          17.9  12.8   8.8      12.0    10.9
2   E03           11.3      10.2          10.6  10.4   5.4       9.4     7.0
3   E04           10.8      12.2           7.7  13.2   4.8      11.1    10.6
4   E05           11.8      11.3           9.6  11.7  10.4       9.9     7.6
5   E06           11.9      11.5          13.9  14.1   8.5       9.3    10.3
6   E07           11.0      11.7          10.1  13.4  13.5       6.3     7.5
7   E08           10.4       9.2          12.8   6.8   5.1       6.7     7.3
8   E09           10.1       8.7          11.0  16.2  13.2       9.4     6.3
9   E10           10.2       7.8          13.9  10.0   3.6       9.4     8.2

In [3]:
data.pop("Eleve")
subjects = list(data.keys())
subjects

['Mathematiques',
 'Physique',
 'Informatique',
 'LV1',
 'LV2',
 'Biologie',
 'Chimie']

In [4]:
notes = data.to_numpy()
notes

array([[12.6, 10.6, 14.2, 12.3, 10.2,  9.3,  7.7],
       [13.9, 12.9, 17.9, 12.8,  8.8, 12. , 10.9],
       [11.3, 10.2, 10.6, 10.4,  5.4,  9.4,  7. ],
       [10.8, 12.2,  7.7, 13.2,  4.8, 11.1, 10.6],
       [11.8, 11.3,  9.6, 11.7, 10.4,  9.9,  7.6],
       [11.9, 11.5, 13.9, 14.1,  8.5,  9.3, 10.3],
       [11. , 11.7, 10.1, 13.4, 13.5,  6.3,  7.5],
       [10.4,  9.2, 12.8,  6.8,  5.1,  6.7,  7.3],
       [10.1,  8.7, 11. , 16.2, 13.2,  9.4,  6.3],
       [10.2,  7.8, 13.9, 10. ,  3.6,  9.4,  8.2]])

In [5]:
notes_pt = torch.tensor(notes, dtype=torch.float64)
notes_pt

tensor([[12.6000, 10.6000, 14.2000, 12.3000, 10.2000,  9.3000,  7.7000],
        [13.9000, 12.9000, 17.9000, 12.8000,  8.8000, 12.0000, 10.9000],
        [11.3000, 10.2000, 10.6000, 10.4000,  5.4000,  9.4000,  7.0000],
        [10.8000, 12.2000,  7.7000, 13.2000,  4.8000, 11.1000, 10.6000],
        [11.8000, 11.3000,  9.6000, 11.7000, 10.4000,  9.9000,  7.6000],
        [11.9000, 11.5000, 13.9000, 14.1000,  8.5000,  9.3000, 10.3000],
        [11.0000, 11.7000, 10.1000, 13.4000, 13.5000,  6.3000,  7.5000],
        [10.4000,  9.2000, 12.8000,  6.8000,  5.1000,  6.7000,  7.3000],
        [10.1000,  8.7000, 11.0000, 16.2000, 13.2000,  9.4000,  6.3000],
        [10.2000,  7.8000, 13.9000, 10.0000,  3.6000,  9.4000,  8.2000]],
       dtype=torch.float64)

In [6]:
# define activation function
activation_fct_relu = torch.nn.ReLU()

# define dense layer and it parameters(7 input features; 2 output features)
linear_filter = torch.nn.Linear(7, 2, bias=True)

In [7]:
linear_filter.weight.data = torch.tensor([[0.2, 0.2, 0.2, 0.0, 0.0, 0.2, 0.2],
                                         [0.0, 0.0, 0.0, 0.5, 0.5, 0.0, 0.0]], 
                                        dtype=torch.float64)
linear_filter.bias.data   = torch.tensor([-10, -10], dtype=torch.float64)

In [8]:
filtered_data = activation_fct_relu(linear_filter(notes_pt[:,:]))
print(filtered_data)

tensor([[0.8800, 1.2500],
        [3.5200, 0.8000],
        [0.0000, 0.0000],
        [0.4800, 0.0000],
        [0.0400, 1.0500],
        [1.3800, 1.3000],
        [0.0000, 3.4500],
        [0.0000, 0.0000],
        [0.0000, 4.7000],
        [0.0000, 0.0000]], dtype=torch.float64, grad_fn=<ReluBackward0>)
